services:
  keycloak:
    build: ./Docker/Keycloak
    depends_on:
      - user_db
    command: start-dev --import-realm
    ports:
      - ${KC_HOST_PORT}:8080
    environment:
      - KEYCLOAK_ADMIN=$KC_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=$KC_ADMIN_PASSWORD
      - KC_DB=postgres
      - KC_DB_URL_HOST=user_db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=$USER_DB_NAME
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
    volumes:
      - type: bind
        source: ./Docker/Keycloak/vigor-dev.json
        target: /opt/keycloak/data/import/vigor-dev.json
        read_only: true

  pgadmin:
    build: ./Docker/PgAdmin
    ports:
      - 2001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  queue:
    build: ./Docker/Core/Queue
    ports:
      - $CORE_BUS_HOST_PORT:6379
    environment:
      - ADMIN_PASSWORD=$CORE_BUS_DEFAULT_PASSWORD
      - MOD_PLATFORM_DB_DISPATCHER_PASSWORD=$CORE_BUS_PLATFORM_DB_DISPATCHER_PASSWORD
      - MOD_PLATFORM_QUEUE_CONSUMER_PASSWORD=$CORE_BUS_PLATFORM_QUEUE_CONSUMER_PASSWORD
      - MOD_USER_DB_DISPATCHER_PASSWORD=$CORE_BUS_USER_DB_DISPATCHER_PASSWORD
      - MOD_USER_QUEUE_CONSUMER_PASSWORD=$CORE_BUS_USER_QUEUE_CONSUMER_PASSWORD

  platform_db:
    build: ./Docker/Core/Platform/Db
    ports:
      - $PLATFORM_DB_HOST_PORT:5432
    environment:
      - POSTGRES_DB=$PLATFORM_DB_NAME
      - POSTGRES_USER=$PLATFORM_DB_USERNAME
      - POSTGRES_PASSWORD=$PLATFORM_DB_PASSWORD

  platform_api_http:
    depends_on:
      - platform_db
      - keycloak
    build:
      context: .
      dockerfile: ./Docker/Core/Platform/Api/Http/Dockerfile
    ports:
      - 4000:8080
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Keycloak__Audience=core-platform
      - Keycloak__Authority=http://keycloak:8080/realms/$KC_REALM
      - Keycloak__Realm=${KC_REALM}
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ServerUrl=http://keycloak:8080
      - Keycloak__ValidIssuers__0=${KC_HOST}:${KC_HOST_PORT}/realms/${KC_REALM}
      - ConnectionStrings__PlatformDb=Host=platform_db;Port=5432;Database=$PLATFORM_DB_NAME;Username=$PLATFORM_DB_USERNAME;Password=$PLATFORM_DB_PASSWORD

  user_db:
    build: ./Docker/Core/User/Db
    ports:
      - $USER_DB_HOST_PORT:5432
    environment:
      - POSTGRES_DB=$USER_DB_NAME
      - POSTGRES_USER=$USER_DB_USERNAME
      - POSTGRES_PASSWORD=$USER_DB_PASSWORD
