services:
  keycloak:
    build: ./Docker/Keycloak
    depends_on:
      - user_db
    command: start-dev
    ports:
      - ${KC_HOST_PORT}:8080
    environment:
      - KEYCLOAK_ADMIN=$KC_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=$KC_ADMIN_PASSWORD
      - KC_DB=postgres
      - KC_DB_URL_HOST=user_db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=$USER_DB_NAME
      - KC_DB_USERNAME
      - KC_DB_PASSWORD

  pgadmin:
    build: ./Docker/PgAdmin
    ports:
      - 2001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      
  queue:
    build: ./Docker/Core/Queue
    ports:
      - $CORE_BUS_HOST_PORT:6379
    environment:
      - ADMIN_PASSWORD=$CORE_BUS_DEFAULT_PASSWORD
      - MOD_PROGRAM_DB_DISPATCHER_PASSWORD=$CORE_BUS_PROGRAM_DB_DISPATCHER_PASSWORD
      - MOD_PROGRAM_QUEUE_CONSUMER_PASSWORD=$CORE_BUS_PROGRAM_QUEUE_CONSUMER_PASSWORD
      - MOD_USER_DB_DISPATCHER_PASSWORD=$CORE_BUS_USER_DB_DISPATCHER_PASSWORD
      - MOD_USER_QUEUE_CONSUMER_PASSWORD=$CORE_BUS_USER_QUEUE_CONSUMER_PASSWORD

  program_db:
    build: ./Docker/Core/Program/Db
    ports:
      - $PROGRAM_DB_HOST_PORT:5432
    environment:
      - POSTGRES_DB=$PROGRAM_DB_NAME
      - POSTGRES_USER=$PROGRAM_DB_USERNAME
      - POSTGRES_PASSWORD=$PROGRAM_DB_PASSWORD

  user_db:
    build: ./Docker/Core/User/Db
    ports:
      - $USER_DB_HOST_PORT:5432
    environment:
      - POSTGRES_DB=$USER_DB_NAME
      - POSTGRES_USER=$USER_DB_USERNAME
      - POSTGRES_PASSWORD=$USER_DB_PASSWORD
