// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Vigor.Core.User.Db.Migrations;

[DbContext(typeof(UserDbContext))]
[Migration("20240824051349_CreateProfileTable")]
partial class CreateProfileTable
{
  protected override void BuildTargetModel(ModelBuilder modelBuilder)
  {
    modelBuilder
        .HasAnnotation("ProductVersion", "8.0.4")
        .HasAnnotation("Relational:MaxIdentifierLength", 63);

    NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

    modelBuilder.Entity("Vigor.Core.User.Db.Models.Profile", b =>
        {
          b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

          NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

          b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

          b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

          b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

          b.HasKey("Id")
                    .HasName("pk_profile");

          b.ToTable("profile", (string)null);
        });
  }
}
