name: Core CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "*core/*" ]

jobs:
  build-and-test:
    name: Build and test ${{ matrix.solution }}
    strategy:
      matrix:
        solution:
          - core/module-auth
          - core/module-contract
          - core/module-user
    uses: ./.github/workflows/_build-and-test-dotnet-solution.yml
    with:
      dotnet-version: 8.0.x
      dotnet-solution-path: ${{ matrix.solution }}

  analyze:
    name: Discover ${{ matrix.language }} vunerabilities
    strategy:
      matrix:
        language: [ "csharp" ]
    permissions:
      security-events: write
      packages: read # required to fetch internal or private CodeQL packs
      contents: read
    uses: ./.github/workflows/_discover-vulnerabilities.yml
    with:
      language: ${{ matrix.language }}
